services:
  torq-db:
    image: postgres:17-alpine
    container_name: torq_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - torq_db_data:/var/lib/postgresql/data
    networks:
      - torq-network

  torq-api:
    build: .
    container_name: torq_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@torq-db:5432/${POSTGRES_DB}?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - torq-db
    networks:
      - torq-network

networks:
  torq-network:
    driver: bridge

volumes:
  torq_db_data: