services:
  torq-db:
    image: postgres:17-alpine
    container_name: torq_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - torq_db_data:/var/lib/postgresql/data
    networks:
      - torq-network

networks:
  torq-network:
    driver: bridge

volumes:
  torq_db_data: